### register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName": "martin",
    "lastName": "Aguirre",
    "emailId": "martin",
    "password": "martin"
}

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "emailId": "martin",
    "password": "martin"
}