### register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName": "Pepe",
    "lastName": "Aguirre",
    "emailId": "pepe",
    "password": "pepe"
}

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "emailId": "pepe",
    "password": "pepe"
}